### PR TITLE
Add ability to toggle editor view

### PR DESCRIPTION
**Pull request by hamin**
Just a small feature that I added for myself and thought would be useful to contribute back :)

### CODE REVIEW

**Comment by lukakerr** [comment]
Awesome! I noticed though that it uses the same keyEquivalent (`⌘ \`) as the toggle preview action. Do you reckon you could change this to something else, maybe `⌘ E` or `Shift ⌘ E`? after that it looks good to merge, thanks!

**Comment by hamin** [comment]
@lukakerr done, I went with `⌘ E `

**Comment by hamin** [comment]
@lukakerr awesome and thank you!. Any chance of a new release build? Trying to promote the use of Twig internally in our company. Primarily honestly as a markdown docs reader , thus the reason I added that toggle :). I LOVE the open folder and sidebar!

**Comment by lukakerr** [comment]
@hamin Good to hear! I'll release a new build sometime in the next few days since there are a few new features since 0.0.1 anyway

**Pull request merged**
